Repository Loopz-Official/spring-vote-21st, pull requests merged in 2025-05, with the labels that each got.

#5 refractor: entity 수정
  src/main/java/com/ceos/vote/candidate/domain/Candidate.java
  src/main/java/com/ceos/vote/user/domain/UserEntity.java
  src/main/java/com/ceos/vote/vote/domain/Vote.java
Labels: ✨ Feature, 🔨 Refactor

#7 feat: 로그인 회원가입 구현
  .gitignore
  build.gradle
  src/main/java/com/ceos/vote/VoteApplication.java
  src/main/java/com/ceos/vote/candidate/domain/Candidate.java
  src/main/java/com/ceos/vote/global/config/OpenApiConfig.java
  src/main/java/com/ceos/vote/global/domain/BaseTimeEntity.java
  src/main/java/com/ceos/vote/global/domain/BaseTimeEntityWithDeletion.java
  src/main/java/com/ceos/vote/global/dto/CommonResponse.java
  src/main/java/com/ceos/vote/global/dto/ResponseError.java
  src/main/java/com/ceos/vote/global/exception/CustomException.java
  src/main/java/com/ceos/vote/global/exception/ErrorCode.java
  src/main/java/com/ceos/vote/global/handler/GlobalExceptionHandler.java
  src/main/java/com/ceos/vote/global/handler/ResponseInterceptor.java
  src/main/java/com/ceos/vote/redis/config/RedisConfig.java
  src/main/java/com/ceos/vote/redis/entity/RefreshToken.java
  src/main/java/com/ceos/vote/redis/repository/RefreshTokenRepository.java
  src/main/java/com/ceos/vote/redis/service/RefreshTokenRedisService.java
  src/main/java/com/ceos/vote/security/config/CorsConfig.java
  src/main/java/com/ceos/vote/security/config/SecurityConfig.java
  src/main/java/com/ceos/vote/security/dto/PrincipalUserDetails.java
  src/main/java/com/ceos/vote/security/dto/request/RequestLogin.java
  src/main/java/com/ceos/vote/security/exception/SecurityErrorCode.java
  src/main/java/com/ceos/vote/security/exception/SecurityImplementErrorCode.java
  src/main/java/com/ceos/vote/security/exception/SecurityImplementException.java
  src/main/java/com/ceos/vote/security/exception/TokenException.java
  src/main/java/com/ceos/vote/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/ceos/vote/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/ceos/vote/security/filter/JwtExceptionFilter.java
  src/main/java/com/ceos/vote/security/handler/JwtAuthenticationFailureHandler.java
  src/main/java/com/ceos/vote/security/handler/JwtAuthenticationSuccessHandler.java
  src/main/java/com/ceos/vote/security/jwt/JwtProvider.java
  src/main/java/com/ceos/vote/security/service/CustomUsersDetailService.java
  src/main/java/com/ceos/vote/user/controller/UserController.java
  src/main/java/com/ceos/vote/user/domain/Role.java
  src/main/java/com/ceos/vote/user/domain/UserEntity.java
  src/main/java/com/ceos/vote/user/dto/UserDto.java
  src/main/java/com/ceos/vote/user/dto/request/RequestJoin.java
  src/main/java/com/ceos/vote/user/exception/AuthErrorCode.java
  src/main/java/com/ceos/vote/user/exception/AuthException.java
  src/main/java/com/ceos/vote/user/repository/UserRepository.java
  src/main/java/com/ceos/vote/user/service/UserService.java
  src/main/java/com/ceos/vote/vote/domain/Vote.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#8 feat: CI CD 구현
  .dockerignore
  .github/workflows/be_deploy.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/java/com/ceos/vote/security/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🌏 Deploy
